# Generated by Django 5.1 on 2024-10-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='current_question_index',
            field=models.IntegerField(default=0),
        ),
    ]
