# Generated by Django 5.1 on 2024-10-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_userprogress_current_question_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
